# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "post" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"author" VARCHAR NOT NULL,"title" VARCHAR NOT NULL,"content" VARCHAR NOT NULL,"updated_at" TIMESTAMP,"created_at" TIMESTAMP NOT NULL);

# --- !Downs

drop table "post";

